### ISSUE TITLE
Install error when zmq is not present in system

### ISSUE THREAD

**Issue by jeffreytgilbert** [mcollina/ascoltatori#109]
Is zmq a core dependency for this lib? I want to use this as a broker because it shouldnt/wouldnt require C installs for the pure node setup with qlobberFS..

Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ~/Documents/node-projects/vision/watson/node_modules/ascoltatori/node_modules/zmq
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

**Comment by mcollina** [comment]
zmq is optional, so npm install should not fail. At least I have not seen
it failing.
Il giorno gio 22 gen 2015 alle 18:36 Jeffrey Gilbert <
notifications@github.com> ha scritto:

**Comment by jeffreytgilbert** [comment]
Remove zmq from your system and try installing. Fails for me every time.

**Comment by mcollina** [comment]
On my system it installs perfectly without zeromq in:

```bash
$ npm install ascoltatori

> hiredis@0.1.17 install /Users/matteocollina/Temp/asc/node_modules/ascoltatori/node_modules/hiredis
> node-gyp rebuild

  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
  LIBTOOL-STATIC Release/hiredis.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/hiredis.node
  SOLINK_MODULE(target) Release/hiredis.node: Finished

> zmq@2.8.0 install /Users/matteocollina/Temp/asc/node_modules/ascoltatori/node_modules/zmq
> node-gyp rebuild

Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/matteocollina/.nvm/v0.10.33/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/Users/matteocollina/.nvm/v0.10.33/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
cwd /Users/matteocollina/Temp/asc/node_modules/ascoltatori/node_modules/zmq
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing zmq@2.8.0

> kerberos@0.0.8 install /Users/matteocollina/Temp/asc/node_modules/ascoltatori/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/kerberos.node
  SOLINK_MODULE(target) Release/kerberos.node: Finished

> bson@0.2.18 install /Users/matteocollina/Temp/asc/node_modules/ascoltatori/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/bson.node
  SOLINK_MODULE(target) Release/bson.node: Finished

> buffertools@2.0.1 install /Users/matteocollina/Temp/asc/node_modules/ascoltatori/node_modules/qlobber-fsq/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/buffertools.node
  SOLINK_MODULE(target) Release/buffertools.node: Finished

> fs-ext@0.3.2 install /Users/matteocollina/Temp/asc/node_modules/ascoltatori/node_modules/qlobber-fsq/node_modules/fs-ext
> node-gyp configure build

  CXX(target) Release/obj.target/fs-ext/fs-ext.o
  SOLINK_MODULE(target) Release/fs-ext.node
  SOLINK_MODULE(target) Release/fs-ext.node: Finished
ascoltatori@0.18.0 node_modules/ascoltatori
├── eventemitter2@0.4.14
├── node-uuid@1.4.2
├── async@0.9.0
├── redis@0.12.1
├── qlobber@0.3.9
├── debug@2.1.1 (ms@0.6.2)
├── mqtt@0.3.13 (readable-stream@1.0.33)
├── hiredis@0.1.17 (bindings@1.2.1, nan@1.1.2)
├── amqp@0.2.0 (lodash@1.3.1)
├── mongodb@1.4.29 (readable-stream@1.0.33, kerberos@0.0.8, bson@0.2.18)
└── qlobber-fsq@0.1.1 (graceful-fs@2.0.3, async@0.2.10, buffertools@2.0.1, fs-ext@0.3.2)
```

The relevant bit is:
```
npm WARN optional dep failed, continuing zmq@2.8.0
```

**Comment by jeffreytgilbert** [comment]
I havent put this into bamboo but my concern is that it would fail due to 

gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1

**Comment by mcollina** [comment]
It does not fail, because it is an optional dependency.
