### ISSUE TITLE
Redis adapter gives TypeError: topic.replace is not a function

### ISSUE THREAD

**Issue by mulderp** [mcollina/ascoltatori#138]
I am trying the Redis example from the Mosca repo. I see an error:

```
/home/vagrant/projects/mqtt_example/node_modules/mosca/node_modules/ascoltatori/lib/redis_ascoltatore.js:135
        topic = topic.replace(new RegExp('/$'), '');
                      ^

TypeError: topic.replace is not a function
    at Immediate._onImmediate (/home/vagrant/projects/mqtt_example/node_modules/mosca/node_modules/ascoltatori/lib/redis_ascoltatore.js:135:23)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

Process information

```
vagrant@vagrant-ubuntu-trusty-64:~/projects/mqtt_example$ node example.js
Mosca server is up and running
client connected mqttjs_6a1d5bc7
Published mqttjs_6a1d5bc7
$SYS/V16bKdZre/new/clients/
```

Example.js

```
var mosca = require('mosca')

var ascoltatore = {
  type: 'redis',
  redis: require('redis'),
  db: 12,
  port: 6379,
  return_buffers: true, // to handle binary payloads
  host: "127.0.0.1",
  debug: true
};

var moscaSettings = {
  port: 1883,
  backend: ascoltatore,
  persistence: {
    factory: mosca.persistence.Redis
  }
};

var server = new mosca.Server(moscaSettings);

server.on('ready', setup);
server.on('clientConnected', function(client) {
  console.log('client connected', client.id);
});

// fired when a message is received
server.on('published', function(packet, client) {
  console.log('Published', packet.payload);
});

// fired when the mqtt server is ready
function setup() {
  console.log('Mosca server is up and running')
}
```

**Comment by shsjshentao** [comment]
i have the same problem

**Comment by dottgonzo** [comment]
+ 1

**Comment by mcollina** [comment]
Fixed in v2.0.0

**Comment by husnulhamidiah** [comment]
Still getting this problem in v2.0.1

**Comment by mcollina** [comment]
Can you please provide a stacktrace?

**Comment by husnulhamidiah** [comment]
````
/home/husnul/skripsi/qoap/node_modules/ascoltatori/lib/abstract_ascoltatore.js:199
    topic = topic.replace(this._reInWildcardOne,
                  ^

TypeError: topic.replace is not a function
    at EventEmitter.AbstractAscoltatore._subTopic (/home/husnul/skripsi/qoap/node_modules/ascoltatori/lib/abstract_ascoltatore.js:199:19)
    at EventEmitter.subscribe (/home/husnul/skripsi/qoap/node_modules/ascoltatori/lib/redis_ascoltatore.js:187:23)
    at Function.Data.subscribe (/home/husnul/skripsi/qoap/lib/models/data.js:135:23)
    at /home/husnul/skripsi/qoap/lib/controllers/mqtt_api.js:48:20
    at Connection.<anonymous> (/home/husnul/skripsi/qoap/lib/controllers/mqtt_api.js:60:14)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection.emitPacket (/home/husnul/skripsi/qoap/node_modules/mqtt-connection/connection.js:13:8)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
````

Here you go. @mcollina 
And I'm using redis v2.5.3

**Comment by mcollina** [comment]
That's a different bug: can you send a PR to address that as well? You will just need to call `topic.toString()` before passing the topic to `_subTopic` : https://github.com/mcollina/ascoltatori/blob/master/lib/redis_ascoltatore.js#L187

Also, are you sure that topic is a value here? I see it's passing through a lot of your code.
