### ISSUE TITLE
ascolatori won't run if optionalDependencies are not installed

### ISSUE THREAD

**Issue by mkj28** [mcollina/ascoltatori#189]
`yarn install --ignore-optional` let's you install ascolatori without pulling in eventemitter2, but then it throws:

Error: Cannot find module 'eventemitter2'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/edge-broker/node_modules/ascoltatori/lib/event_emitter2_ascoltatore.js:7:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/edge-broker/node_modules/ascoltatori/lib/ascoltatori.js:13:43)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/edge-broker/node_modules/ascoltatori/index.js:2:18)

**Comment by mvayngrib** [comment]
maybe the exports can be lazy-evaluated, via defineProperty, and a getter
